# Test 2024-03-13 at 04:37:34

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SvgSimple
        path: svg

    - name: Cpan
      run:  sudo cpan install -T Data::Dump

    - name: Test Silicon Layout
      run:
        perl -Idtt/lib -Isvg/lib  lib/Silicon/Chip/Layout.pm
