# Test 2024-04-06 at 06:58:06

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/GithubCrud
        path: gh

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SvgSimple
        path: svg

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/MathIntersectionCircleLine
        path: micl

    - name: Cpan
      run:  sudo cpan install -T Data::Dump Digest::SHA1

    - name: Test Silicon Layout
      run:
        perl -Idtt/lib -Isvg/lib  -Imicl/lib  lib/Silicon/Chip/Layout.pm

    - name: Upload images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tree
        perl -Idtt/lib -Igh/lib -MGitHub::Crud -e"&GitHub::Crud::writeFolderUsingSavedToken(@ARGV)" -- philiprbrenan SiliconChipWiring lib/Silicon/Chip/svg/ svg/

    - uses: actions/upload-artifact@v4
      with:
        name: Layouts
        path: |
          svg

