# Test 2024-04-09 at 02:26:25

name: Test

on:
  push

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/GithubCrud
        path: gh

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SvgSimple
        path: svg

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/MathIntersectionCircleLine
        path: micl

    - name: Install Cairo svg
      run:
        sudo apt install cairosvg

    - name: Cpan
      run:  sudo cpan install -T Data::Dump Digest::SHA1

    - name: Test Silicon Layout
      run:
        perl -Idtt/lib -Isvg/lib  -Imicl/lib  lib/Silicon/Chip/Layout.pm

    - name: Upload images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tree
        perl -Idtt/lib -Igh/lib -M"Data::Table::Text" -e"Data::Table::Text::postProcessImagesForDocumentation"

    - uses: actions/upload-artifact@v4
      with:
        name: Layouts
        path: |
          svg

